import type { IComponent } from '../../models/Component.model.js';
import * as componentRepo from '../../repositories/componentRepository.js';

const COMPONENTS: Partial<IComponent>[] = [
  {
    slug: 'user',
    name: 'User / Client',
    category: 'client',
    icon: 'user',
    purpose: 'End users interact with the system through web, mobile, or desktop clients.',
    responsibilities: ['Initiate requests', 'Render UI', 'Handle client-side caching'],
    advantages: ['Direct user interaction', 'Can offload work to edge'],
    disadvantages: ['Unreliable network', 'Limited compute on mobile'],
    alternatives: [{ name: 'Thin Client', description: 'Minimal client logic', whenToUse: 'When all logic is server-side' }],
    tradeoffs: ['Rich client vs thin client', 'Native vs web apps'],
    scalingConsiderations: ['CDN for static assets', 'Client-side caching strategies'],
    interviewQuestions: [
      { question: 'How do you handle offline mode?', category: 'conceptual' },
      { question: 'Web vs native mobile tradeoffs?', category: 'tradeoff' },
    ],
    realWorldExamples: ['Twitter mobile app', 'WhatsApp Web'],
    simulation: { baseCapacityRps: 1000000, cpuPerRps: 0, memoryMbBase: 0, memoryPerRps: 0, latencyMsBase: 0, latencyPerRpsFactor: 0, fanOut: 1 },
    failure: { userFacingImpact: 'Cannot access the application', internalImpact: 'No incoming traffic', recoveryMechanisms: ['N/A - client-side'], industryMitigations: ['Offline mode', 'Retry with backoff'], dependentComponents: [], cascadeSeverity: 'none' },
    cost: { unitType: 'client', unitPriceMonthly: 0, minUnits: 0, scalingFactor: 0 },
  },
  {
    slug: 'dns',
    name: 'DNS',
    category: 'network',
    icon: 'dns',
    purpose: 'Translates domain names to IP addresses, enabling service discovery.',
    responsibilities: ['Domain resolution', 'Load distribution via DNS routing', 'Health-aware routing'],
    advantages: ['Global distribution', 'Low latency lookups', 'TTL-based caching'],
    disadvantages: ['Propagation delays', 'Limited routing logic'],
    alternatives: [{ name: 'Service Discovery', description: 'Consul, Eureka', whenToUse: 'Internal microservice routing' }],
    tradeoffs: ['TTL vs freshness', 'GeoDNS vs anycast'],
    scalingConsiderations: ['Use managed DNS (Route53, Cloudflare)', 'Low TTL for failover'],
    interviewQuestions: [
      { question: 'How does DNS-based load balancing work?', category: 'conceptual' },
      { question: 'What happens when DNS fails?', category: 'failure' },
    ],
    realWorldExamples: ['Route53', 'Cloudflare DNS'],
    simulation: { baseCapacityRps: 500000, cpuPerRps: 0.0001, memoryMbBase: 64, memoryPerRps: 0.001, latencyMsBase: 2, latencyPerRpsFactor: 0.00001, fanOut: 1 },
    failure: { userFacingImpact: 'Users cannot resolve domain — complete outage', internalImpact: 'No traffic reaches infrastructure', recoveryMechanisms: ['Secondary DNS provider', 'Lower TTL before migration'], industryMitigations: ['Multi-provider DNS', 'Anycast DNS'], dependentComponents: ['cdn', 'load-balancer'], cascadeSeverity: 'full' },
    cost: { unitType: 'zone', unitPriceMonthly: 5, minUnits: 1, scalingFactor: 0 },
  },
  {
    slug: 'cdn',
    name: 'CDN',
    category: 'network',
    icon: 'cdn',
    purpose: 'Distributes static and dynamic content globally to reduce latency.',
    responsibilities: ['Cache static assets', 'Edge compute', 'DDoS protection at edge'],
    advantages: ['Reduced latency', 'Lower origin load', 'Global reach'],
    disadvantages: ['Cache invalidation', 'Cost at scale', 'Dynamic content challenges'],
    alternatives: [{ name: 'Origin-only', description: 'Serve from origin', whenToUse: 'Low traffic or highly dynamic content' }],
    tradeoffs: ['Cache hit ratio vs freshness', 'Push vs pull CDN'],
    scalingConsiderations: ['Edge locations', 'Cache key design', 'Origin shield'],
    interviewQuestions: [
      { question: 'How do you invalidate CDN cache?', category: 'conceptual' },
      { question: 'CDN vs load balancer?', category: 'tradeoff' },
    ],
    realWorldExamples: ['CloudFront', 'Cloudflare', 'Akamai'],
    simulation: { baseCapacityRps: 500000, cpuPerRps: 0.0005, memoryMbBase: 128, memoryPerRps: 0.002, latencyMsBase: 5, latencyPerRpsFactor: 0.00005, cacheHitRateDefault: 0.92, fanOut: 0.08 },
    failure: { userFacingImpact: 'Slow page loads, images fail to load', internalImpact: 'All traffic hits origin servers directly', recoveryMechanisms: ['Failover to secondary CDN', 'Origin scaling'], industryMitigations: ['Multi-CDN strategy', 'Origin capacity buffer'], dependentComponents: ['load-balancer', 'application-server'], cascadeSeverity: 'partial' },
    cost: { unitType: 'tb', unitPriceMonthly: 85, minUnits: 1, scalingFactor: 0.3 },
  },
  {
    slug: 'load-balancer',
    name: 'Load Balancer',
    category: 'network',
    icon: 'load-balancer',
    purpose: 'Distributes incoming traffic across multiple backend servers.',
    responsibilities: ['Traffic distribution', 'Health checks', 'SSL termination'],
    advantages: ['High availability', 'Horizontal scaling enabler', 'SSL offloading'],
    disadvantages: ['Single point of failure if not redundant', 'Session stickiness complexity'],
    alternatives: [{ name: 'DNS Load Balancing', description: 'Round-robin DNS', whenToUse: 'Simple deployments' }],
    tradeoffs: ['L4 vs L7 balancing', 'Round-robin vs least connections'],
    scalingConsiderations: ['Active-active LB pairs', 'Auto-scaling integration'],
    interviewQuestions: [
      { question: 'L4 vs L7 load balancer?', category: 'tradeoff' },
      { question: 'What happens if load balancer goes down?', category: 'failure' },
    ],
    realWorldExamples: ['AWS ALB', 'NGINX', 'HAProxy'],
    simulation: { baseCapacityRps: 200000, cpuPerRps: 0.001, memoryMbBase: 128, memoryPerRps: 0.002, latencyMsBase: 3, latencyPerRpsFactor: 0.00005, fanOut: 1 },
    failure: { userFacingImpact: 'Complete service unavailability', internalImpact: 'No traffic reaches application servers', recoveryMechanisms: ['Active-passive failover', 'Anycast IP failover'], industryMitigations: ['Multi-AZ deployment', 'Health check automation'], dependentComponents: ['application-server', 'api-gateway'], cascadeSeverity: 'full' },
    cost: { unitType: 'instance', unitPriceMonthly: 25, minUnits: 2, scalingFactor: 0.1 },
  },
  {
    slug: 'api-gateway',
    name: 'API Gateway',
    category: 'gateway',
    icon: 'api-gateway',
    purpose: 'Single entry point for API requests with routing, auth, and rate limiting.',
    responsibilities: ['Request routing', 'Authentication', 'Rate limiting', 'Request/response transformation'],
    advantages: ['Centralized cross-cutting concerns', 'API versioning', 'Protocol translation'],
    disadvantages: ['Additional latency hop', 'Potential bottleneck', 'Configuration complexity'],
    alternatives: [{ name: 'Direct service access', description: 'Clients call services directly', whenToUse: 'Internal microservices with service mesh' }],
    tradeoffs: ['Centralized vs decentralized gateway', 'Sync vs async routing'],
    scalingConsiderations: ['Horizontal scaling', 'Circuit breakers', 'Caching at gateway'],
    interviewQuestions: [
      { question: 'Why use an API gateway?', category: 'conceptual' },
      { question: 'API gateway vs load balancer?', category: 'tradeoff' },
    ],
    realWorldExamples: ['Kong', 'AWS API Gateway', 'Envoy'],
    simulation: { baseCapacityRps: 100000, cpuPerRps: 0.002, memoryMbBase: 256, memoryPerRps: 0.003, latencyMsBase: 5, latencyPerRpsFactor: 0.0001, fanOut: 1 },
    failure: { userFacingImpact: 'All API requests fail with 503', internalImpact: 'Services unreachable from external clients', recoveryMechanisms: ['Gateway cluster failover', 'Bypass gateway for critical paths'], industryMitigations: ['Multi-region gateways', 'Circuit breakers'], dependentComponents: ['application-server'], cascadeSeverity: 'full' },
    cost: { unitType: 'instance', unitPriceMonthly: 80, minUnits: 2, scalingFactor: 0.2 },
  },
  {
    slug: 'application-server',
    name: 'Application Server',
    category: 'compute',
    icon: 'application-server',
    purpose: 'Executes business logic and processes user requests.',
    responsibilities: ['Business logic', 'Request validation', 'Orchestration of downstream services'],
    advantages: ['Flexible scaling', 'Technology choice freedom', 'Stateless horizontal scaling'],
    disadvantages: ['Requires load balancing', 'State management complexity'],
    alternatives: [{ name: 'Serverless', description: 'Lambda, Cloud Functions', whenToUse: 'Variable/spiky workloads' }],
    tradeoffs: ['Monolith vs microservices', 'Sync vs async processing'],
    scalingConsiderations: ['Auto-scaling groups', 'Stateless design', 'Connection pooling'],
    interviewQuestions: [
      { question: 'How do you scale application servers?', category: 'scaling' },
      { question: 'Stateful vs stateless servers?', category: 'tradeoff' },
    ],
    realWorldExamples: ['Node.js services', 'Java Spring Boot', 'Go microservices'],
    simulation: { baseCapacityRps: 5000, cpuPerRps: 0.01, memoryMbBase: 512, memoryPerRps: 0.02, latencyMsBase: 10, latencyPerRpsFactor: 0.001, fanOut: 2 },
    failure: { userFacingImpact: 'Increased errors and latency', internalImpact: 'Reduced processing capacity', recoveryMechanisms: ['Auto-scaling', 'Circuit breakers to dependencies'], industryMitigations: ['Multi-AZ deployment', 'Graceful degradation'], dependentComponents: ['redis', 'database', 'queue'], cascadeSeverity: 'partial' },
    cost: { unitType: 'instance', unitPriceMonthly: 120, minUnits: 2, scalingFactor: 1 },
  },
  {
    slug: 'redis',
    name: 'Redis',
    category: 'cache',
    icon: 'redis',
    purpose: 'In-memory data store used as cache, session store, and message broker.',
    responsibilities: ['Cache hot data', 'Session storage', 'Rate limiting counters', 'Pub/Sub messaging'],
    advantages: ['Sub-millisecond latency', 'Rich data structures', 'Persistence options'],
    disadvantages: ['Memory-bound', 'Single-threaded for commands', 'Cache invalidation complexity'],
    alternatives: [{ name: 'Memcached', description: 'Simple key-value cache', whenToUse: 'Simple GET/SET caching only' }],
    tradeoffs: ['Redis vs Memcached', 'Cache-aside vs write-through'],
    scalingConsiderations: ['Redis Cluster', 'Consistent hashing', 'TTL strategies'],
    interviewQuestions: [
      { question: 'Why Redis over Memcached?', category: 'tradeoff' },
      { question: 'What is cache invalidation?', category: 'conceptual' },
      { question: 'What happens if Redis goes down?', category: 'failure' },
      { question: 'Redis persistence options?', category: 'conceptual' },
    ],
    realWorldExamples: ['Twitter timeline cache', 'Session stores', 'Leaderboards'],
    simulation: { baseCapacityRps: 100000, cpuPerRps: 0.001, memoryMbBase: 512, memoryPerRps: 0.01, latencyMsBase: 1, latencyPerRpsFactor: 0.0001, cacheHitRateDefault: 0.85, fanOut: 0.15 },
    failure: { userFacingImpact: 'Increased latency, potential timeouts', internalImpact: 'Database load spikes 5-10x (cache miss storm)', recoveryMechanisms: ['Failover to replica', 'Circuit breaker to DB'], industryMitigations: ['Redis Cluster', 'Multi-AZ', 'Local in-process cache'], dependentComponents: ['database', 'application-server'], cascadeSeverity: 'partial' },
    cost: { unitType: 'node', unitPriceMonthly: 150, minUnits: 2, scalingFactor: 0.5 },
  },
  {
    slug: 'kafka',
    name: 'Kafka',
    category: 'messaging',
    icon: 'kafka',
    purpose: 'Distributed event streaming platform for high-throughput async messaging.',
    responsibilities: ['Event ingestion', 'Stream processing', 'Decoupling producers and consumers'],
    advantages: ['High throughput', 'Durability', 'Replay capability'],
    disadvantages: ['Operational complexity', 'Not ideal for task queues', 'Learning curve'],
    alternatives: [{ name: 'RabbitMQ', description: 'Traditional message broker', whenToUse: 'Complex routing, lower throughput' }],
    tradeoffs: ['Kafka vs RabbitMQ', 'At-least-once vs exactly-once'],
    scalingConsiderations: ['Partition count', 'Consumer groups', 'Retention policies'],
    interviewQuestions: [
      { question: 'Why Kafka?', category: 'conceptual' },
      { question: 'What are partitions?', category: 'conceptual' },
      { question: 'What are consumer groups?', category: 'conceptual' },
      { question: 'Ordering guarantees?', category: 'tradeoff' },
      { question: 'Exactly once semantics?', category: 'conceptual' },
    ],
    realWorldExamples: ['LinkedIn activity feed', 'Uber trip events', 'Netflix data pipeline'],
    simulation: { baseCapacityRps: 200000, cpuPerRps: 0.0005, memoryMbBase: 1024, memoryPerRps: 0.005, latencyMsBase: 3, latencyPerRpsFactor: 0.00005, queueCapacity: 1000000, fanOut: 1 },
    failure: { userFacingImpact: 'Delayed notifications and async processing', internalImpact: 'Event backlog grows, downstream services starved', recoveryMechanisms: ['Broker failover', 'Consumer catch-up'], industryMitigations: ['Multi-broker clusters', 'MirrorMaker replication'], dependentComponents: ['queue', 'notification-service'], cascadeSeverity: 'partial' },
    cost: { unitType: 'cluster', unitPriceMonthly: 400, minUnits: 1, scalingFactor: 0.3 },
  },
  {
    slug: 'queue',
    name: 'Message Queue',
    category: 'messaging',
    icon: 'queue',
    purpose: 'Async message buffer decoupling producers from consumers.',
    responsibilities: ['Buffer messages', 'Ensure delivery', 'Enable async processing'],
    advantages: ['Decoupling', 'Peak load absorption', 'Retry mechanisms'],
    disadvantages: ['Added complexity', 'Message ordering challenges', 'Potential message loss'],
    alternatives: [{ name: 'Kafka', description: 'Event streaming', whenToUse: 'High throughput event logs' }],
    tradeoffs: ['Push vs pull queues', 'FIFO vs priority queues'],
    scalingConsiderations: ['Multiple queues by domain', 'Dead letter queues', 'Consumer scaling'],
    interviewQuestions: [
      { question: 'When to use a message queue?', category: 'conceptual' },
      { question: 'How do you handle poison messages?', category: 'failure' },
    ],
    realWorldExamples: ['Email sending queues', 'Image processing pipelines'],
    simulation: { baseCapacityRps: 50000, cpuPerRps: 0.002, memoryMbBase: 256, memoryPerRps: 0.01, latencyMsBase: 5, latencyPerRpsFactor: 0.0002, queueCapacity: 100000, fanOut: 1 },
    failure: { userFacingImpact: 'Delayed processing (emails, notifications)', internalImpact: 'Backlog accumulation, consumer starvation', recoveryMechanisms: ['Dead letter queue', 'Consumer auto-scaling'], industryMitigations: ['Multi-AZ queues', 'Message persistence'], dependentComponents: ['notification-service'], cascadeSeverity: 'partial' },
    cost: { unitType: 'queue', unitPriceMonthly: 50, minUnits: 1, scalingFactor: 0.2 },
  },
  {
    slug: 'database',
    name: 'Database',
    category: 'database',
    icon: 'database',
    purpose: 'Persistent storage for structured application data with ACID guarantees.',
    responsibilities: ['Data persistence', 'Transactions', 'Query processing'],
    advantages: ['ACID compliance', 'Complex queries', 'Mature ecosystem'],
    disadvantages: ['Scaling writes is hard', 'Single point of failure without replication'],
    alternatives: [{ name: 'NoSQL', description: 'MongoDB, Cassandra', whenToUse: 'Flexible schema, horizontal scaling' }],
    tradeoffs: ['SQL vs NoSQL', 'Normalization vs denormalization'],
    scalingConsiderations: ['Read replicas', 'Sharding', 'Connection pooling'],
    interviewQuestions: [
      { question: 'Replication strategies?', category: 'scaling' },
      { question: 'Sharding approaches?', category: 'scaling' },
      { question: 'CAP theorem implications?', category: 'tradeoff' },
    ],
    realWorldExamples: ['PostgreSQL', 'MySQL', 'Amazon RDS'],
    simulation: { baseCapacityRps: 10000, cpuPerRps: 0.005, memoryMbBase: 2048, memoryPerRps: 0.05, latencyMsBase: 15, latencyPerRpsFactor: 0.002, fanOut: 0 },
    failure: { userFacingImpact: 'Data unavailable, write failures', internalImpact: 'Complete data layer outage', recoveryMechanisms: ['Failover to replica', 'Point-in-time recovery'], industryMitigations: ['Multi-AZ RDS', 'Automated backups', 'Read replicas'], dependentComponents: ['application-server', 'read-replica'], cascadeSeverity: 'full' },
    cost: { unitType: 'instance', unitPriceMonthly: 350, minUnits: 1, scalingFactor: 0.3 },
  },
  {
    slug: 'read-replica',
    name: 'Read Replica',
    category: 'database',
    icon: 'read-replica',
    purpose: 'Read-only copy of primary database offloading read traffic.',
    responsibilities: ['Serve read queries', 'Reduce primary DB load', 'Geographic read distribution'],
    advantages: ['Scale reads horizontally', 'Disaster recovery', 'Analytics offload'],
    disadvantages: ['Replication lag', 'Eventual consistency', 'Additional cost'],
    alternatives: [{ name: 'Cache layer', description: 'Redis for hot reads', whenToUse: 'When data can be eventually consistent' }],
    tradeoffs: ['Sync vs async replication', 'Read-your-writes consistency'],
    scalingConsiderations: ['Multiple replicas', 'Route reads by lag tolerance'],
    interviewQuestions: [
      { question: 'How do you handle replication lag?', category: 'failure' },
      { question: 'When to read from replica vs primary?', category: 'tradeoff' },
    ],
    realWorldExamples: ['MySQL read replicas', 'PostgreSQL streaming replication'],
    simulation: { baseCapacityRps: 30000, cpuPerRps: 0.003, memoryMbBase: 2048, memoryPerRps: 0.03, latencyMsBase: 10, latencyPerRpsFactor: 0.001, fanOut: 0 },
    failure: { userFacingImpact: 'Stale data shown to users', internalImpact: 'Reads fall back to primary, increasing load', recoveryMechanisms: ['Promote replica', 'Redirect reads to other replicas'], industryMitigations: ['Multiple replicas', 'Lag monitoring'], dependentComponents: ['database'], cascadeSeverity: 'partial' },
    cost: { unitType: 'instance', unitPriceMonthly: 250, minUnits: 1, scalingFactor: 0.5 },
  },
  {
    slug: 'search-service',
    name: 'Search Service',
    category: 'search',
    icon: 'search-service',
    purpose: 'Full-text search and indexing for fast query responses.',
    responsibilities: ['Index documents', 'Full-text search', 'Faceted search', 'Autocomplete'],
    advantages: ['Fast text search', 'Relevance scoring', 'Aggregations'],
    disadvantages: ['Index sync complexity', 'Additional infrastructure', 'Memory intensive'],
    alternatives: [{ name: 'Database LIKE queries', description: 'SQL pattern matching', whenToUse: 'Small datasets only' }],
    tradeoffs: ['Elasticsearch vs Solr', 'Near real-time vs batch indexing'],
    scalingConsiderations: ['Sharding indices', 'Replica shards', 'Index lifecycle management'],
    interviewQuestions: [
      { question: 'How do you keep search index in sync?', category: 'conceptual' },
      { question: 'Elasticsearch vs database search?', category: 'tradeoff' },
    ],
    realWorldExamples: ['Elasticsearch', 'Apache Solr', 'Amazon OpenSearch'],
    simulation: { baseCapacityRps: 40000, cpuPerRps: 0.003, memoryMbBase: 4096, memoryPerRps: 0.02, latencyMsBase: 20, latencyPerRpsFactor: 0.0005, fanOut: 0 },
    failure: { userFacingImpact: 'Search functionality unavailable', internalImpact: 'Fallback to database queries (slow)', recoveryMechanisms: ['Replica failover', 'Rebuild from snapshots'], industryMitigations: ['Multi-node clusters', 'Cross-cluster replication'], dependentComponents: ['application-server'], cascadeSeverity: 'partial' },
    cost: { unitType: 'instance', unitPriceMonthly: 200, minUnits: 2, scalingFactor: 0.3 },
  },
  {
    slug: 'object-storage',
    name: 'Object Storage',
    category: 'storage',
    icon: 'object-storage',
    purpose: 'Scalable storage for unstructured data like images, videos, and files.',
    responsibilities: ['Store blobs', 'Serve media files', 'Backup storage'],
    advantages: ['Unlimited scale', 'Durability (11 nines)', 'Cost effective'],
    disadvantages: ['Higher latency than block storage', 'Not suitable for databases'],
    alternatives: [{ name: 'Block storage', description: 'EBS, persistent disks', whenToUse: 'Database storage' }],
    tradeoffs: ['S3 vs GCS vs Azure Blob', 'Storage classes (hot/cold)'],
    scalingConsiderations: ['Lifecycle policies', 'CDN integration', 'Multipart uploads'],
    interviewQuestions: [
      { question: 'Object storage vs block storage?', category: 'tradeoff' },
      { question: 'How do you serve large files efficiently?', category: 'scaling' },
    ],
    realWorldExamples: ['Amazon S3', 'Google Cloud Storage', 'Azure Blob'],
    simulation: { baseCapacityRps: 100000, cpuPerRps: 0.0002, memoryMbBase: 64, memoryPerRps: 0.001, latencyMsBase: 30, latencyPerRpsFactor: 0.0001, fanOut: 0 },
    failure: { userFacingImpact: 'Media files fail to load', internalImpact: 'Upload failures, backup disruption', recoveryMechanisms: ['Cross-region replication', 'Versioning rollback'], industryMitigations: ['Multi-region buckets', 'CRR'], dependentComponents: ['cdn'], cascadeSeverity: 'partial' },
    cost: { unitType: 'tb', unitPriceMonthly: 23, minUnits: 1, scalingFactor: 0.5 },
  },
  {
    slug: 'notification-service',
    name: 'Notification Service',
    category: 'notification',
    icon: 'notification-service',
    purpose: 'Delivers push notifications, emails, and SMS to users.',
    responsibilities: ['Push notifications', 'Email delivery', 'SMS delivery', 'Notification preferences'],
    advantages: ['Multi-channel delivery', 'Template management', 'Delivery tracking'],
    disadvantages: ['Third-party dependencies', 'Rate limits from providers'],
    alternatives: [{ name: 'Direct provider integration', description: 'SendGrid, FCM directly', whenToUse: 'Simple notification needs' }],
    tradeoffs: ['Push vs pull notifications', 'Sync vs async delivery'],
    scalingConsiderations: ['Queue-based delivery', 'Batch notifications', 'Provider failover'],
    interviewQuestions: [
      { question: 'How do you scale notification delivery?', category: 'scaling' },
      { question: 'At-least-once vs exactly-once delivery?', category: 'tradeoff' },
    ],
    realWorldExamples: ['Firebase Cloud Messaging', 'Amazon SNS', 'SendGrid'],
    simulation: { baseCapacityRps: 30000, cpuPerRps: 0.002, memoryMbBase: 256, memoryPerRps: 0.005, latencyMsBase: 50, latencyPerRpsFactor: 0.0003, fanOut: 0 },
    failure: { userFacingImpact: 'Users miss notifications', internalImpact: 'Notification backlog', recoveryMechanisms: ['Retry queue', 'Fallback provider'], industryMitigations: ['Multi-provider setup', 'Dead letter handling'], dependentComponents: ['queue', 'kafka'], cascadeSeverity: 'partial' },
    cost: { unitType: 'instance', unitPriceMonthly: 75, minUnits: 2, scalingFactor: 0.2 },
  },
];

export async function seedComponents(): Promise<void> {
  console.log('Seeding components...');
  await componentRepo.upsertComponents(COMPONENTS);
  console.log(`  ✓ ${COMPONENTS.length} components seeded`);
}
